name: ZhihuFunds
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    PRODUCT_BUNDLE_IDENTIFIER: io.github.qf666.zhihufunds
    PRODUCT_NAME: ZhihuFunds
    TARGETED_DEVICE_FAMILY: 1,2
    DEVELOPMENT_LANGUAGE: zh-Hans
    SUPPORTS_MACCATALYST: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
targets:
  ZhihuFunds:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - src/core
      - src/zhihu
    dependencies:
      - sdk: Charts.framework
    info:
      path: src/zhihu/Info.plist
      properties:
        CFBundleDisplayName: 基金助手
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon60x60
            CFBundleIconName: AppIcon
          CFBundleAlternateIcons:
            AppIconDeep:
              CFBundleIconFiles:
                - AppIconDeep20
                - AppIconDeep29
                - AppIconDeep40
                - AppIconDeep60
                - AppIconDeep76
                - AppIconDeep83p5
            AppIconEmerald:
              CFBundleIconFiles:
                - AppIconEmerald20
                - AppIconEmerald29
                - AppIconEmerald40
                - AppIconEmerald60
                - AppIconEmerald76
                - AppIconEmerald83p5
        CFBundleIcons~ipad:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon60x60
              - AppIcon76x76
            CFBundleIconName: AppIcon
          CFBundleAlternateIcons:
            AppIconDeep:
              CFBundleIconFiles:
                - AppIconDeep20
                - AppIconDeep29
                - AppIconDeep40
                - AppIconDeep60
                - AppIconDeep76
                - AppIconDeep83p5
            AppIconEmerald:
              CFBundleIconFiles:
                - AppIconEmerald20
                - AppIconEmerald29
                - AppIconEmerald40
                - AppIconEmerald60
                - AppIconEmerald76
                - AppIconEmerald83p5
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        LSRequiresIPhoneOS: true
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
    scheme:
      gatherCoverageData: false
