name: ZhihuFunds
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    MARKETING_VERSION: 1.0.10
    CURRENT_PROJECT_VERSION: 10
    PRODUCT_BUNDLE_IDENTIFIER: io.github.qf666.zhihufunds
    PRODUCT_NAME: ZhihuFunds
    TARGETED_DEVICE_FAMILY: 1,2
    DEVELOPMENT_LANGUAGE: zh-Hans
    SUPPORTS_MACCATALYST: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: AppIconDeep AppIconEmerald
    ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
targets:
  ZhihuFunds:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - src/core
      - src/zhihu
    dependencies:
      - sdk: Charts.framework
    info:
      path: src/zhihu/Info.plist
      properties:
        CFBundleDisplayName: 基金助手
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        LSRequiresIPhoneOS: true
        CFBundleShortVersionString: 1.0.10
        CFBundleVersion: 10
    scheme:
      gatherCoverageData: false
